name: Build and Release GT3 AI Coaching

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        npm install
        npm install electron-updater electron-builder
        pip install -r python-server/requirements.txt
    
    - name: Build React app
      run: npm run build
    
    - name: Copy updater files
      run: |
        Copy-Item "electron-updater.js" "build/"
        Copy-Item "preload-updater.js" "build/"
    
    - name: Build Electron app with auto-updater
      run: npx electron-builder --config package-electron.json
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.exe.blockmap
          dist/latest.yml
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
